---
- name: Configure local machine
  hosts: localhost
  become: yes

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"
      changed_when: false
      tags:
        - always

  roles:
    - common
    # Other roles will be added here as we create them

  tags:
    - always
