---
- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: "{{ personal_git_email }}"
  tags:
    - git-personal

- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "{{ git_name }}"
  tags:
    - git-personal

- name: Set default branch name to main
  git_config:
    name: init.defaultBranch
    scope: global
    value: main
  tags:
    - git-config

- name: Set pull behavior to rebase
  git_config:
    name: pull.rebase
    scope: global
    value: "true"
  tags:
    - git-config

- name: Enable Git credential helper
  git_config:
    name: credential.helper
    scope: global
    value: cache --timeout=3600
  tags:
    - git-config

# Work-specific Git configuration
- name: Git work setup email
  git_config:
    name: user.email
    scope: global
    value: "{{ work_git_email }}"
  when: work_git_email is defined
  tags:
    - git-work
