- name: Install System Packages
  become: true
  apt:
    name: ["build-essential", "cmake", "pkg-config"]
  tags:
    - Install
    - neovim
    - core

- name: Install More Packages (lua, unzip, libtools)
  become: true
  apt: ["lua5.3", "unzip", "libtool", "libtool-bin"]
  tags:
    - Install
    - neovim
    - core


