---
- name: LaTeX Setup
  hosts: localhost
  become: true
  tags: 
    - latex

  tasks:
    - name: Install TeX Live and LaTeX packages
      apt:
        name:
          - texlive-full
          - texlive-fonts-recommended
          - texlive-latex-extra
          - texlive-fonts-extra
          - texlive-lang-english
        state: latest
        update_cache: yes
      tags: 
        - latex-install
