- name: Install ZSH
  apt: name=zsh
  tags: &tags_for_zsh_tasks [ 'install', 'productivity', 'dotfiles', 'zsh' ]
    
- name: Change shell to zsh
  command: chsh -s $(which zsh)
  tags: *tags_for_zsh_tasks

