---
- name: Ensure sw directory exists
  file:
    path: "{{ ansible_env.HOME }}/sw"
    state: directory
    mode: '0755'

- name: Clone dotfiles repository
  git:
    repo: "{{ dotfiles_repo }}"
    version: "{{ dotfiles_version | default('main') }}"
    dest: "{{ ansible_env.HOME }}/sw/dotfiles"
    accept_hostkey: yes
    update: yes

- name: Include Zsh setup tasks
  include_tasks: zsh.yml

- name: Create symlinks for other dotfiles
  file:
    src: "{{ ansible_env.HOME }}/sw/dotfiles/{{ item.src }}"
    dest: "{{ ansible_env.HOME }}/{{ item.dest }}"
    state: link
    force: yes
  loop:
    - { src: 'nvim', dest: '.config/nvim' }
