---
- name: Ensure Zsh is installed
  apt:
    name: zsh
    state: present
  become: yes

- name: Get Zsh path
  command: which zsh
  register: zsh_path
  changed_when: false

- name: Set Zsh as default shell
  user:
    name: "{{ ansible_env.USER }}"
    shell: "{{ zsh_path.stdout }}"
  become: yes

- name: Create symlinks for Zsh configuration
  file:
    src: "{{ ansible_env.HOME }}/sw/dotfiles/{{ item.src }}"
    dest: "{{ ansible_env.HOME }}/{{ item.dest }}"
    state: link
    force: yes
  loop:
    - { src: 'zsh/.zshrc', dest: '.zshrc' }
    - { src: 'zsh/.zshenv', dest: '.zshenv' }
    - { src: 'zsh/.p10k.zsh', dest: '.p10k.zsh' }

- name: Ensure Zsh plugins directory exists
  file:
    path: "{{ ansible_env.HOME }}/sw/dotfiles/zsh/plugins"
    state: directory
    mode: '0755'

- name: Clone Zsh plugins
  git:
    repo: "{{ item.repo }}"
    dest: "{{ ansible_env.HOME }}/sw/dotfiles/zsh/plugins/{{ item.name }}"
    version: "{{ item.version | default('HEAD') }}"
    depth: 1
  loop:
    - { name: 'fast-syntax-highlighting', repo: 'https://github.com/zdharma-continuum/fast-syntax-highlighting.git' }
    - { name: 'zsh-autosuggestions', repo: 'https://github.com/zsh-users/zsh-autosuggestions.git' }
    - { name: 'zsh-completions', repo: 'https://github.com/zsh-users/zsh-completions.git' }
    - { name: 'zsh-autocomplete', repo: 'https://github.com/marlonrichert/zsh-autocomplete.git' }

- name: Clone Powerlevel10k theme
  git:
    repo: 'https://github.com/romkatv/powerlevel10k.git'
    dest: "{{ ansible_env.HOME }}/sw/dotfiles/zsh/themes/powerlevel10k"
    version: HEAD
    depth: 1
