- name: Ensure .ssh directory exists
  file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    mode: '0700'

- name: Add SSH private key (Ed25519)
  copy:
    content: "{{ ssh_private_key }}"
    dest: "{{ ansible_env.HOME }}/.ssh/id_ed25519"
    mode: '0600'
  when: ssh_private_key is defined
  register: ssh_key_added

- name: Add SSH public key (Ed25519)
  copy:
    content: "{{ ssh_public_key }}"
    dest: "{{ ansible_env.HOME }}/.ssh/id_ed25519.pub"
    mode: '0644'
  when: ssh_public_key is defined

- name: Ensure GitHub's SSH key is known
  known_hosts:
    name: github.com
    key: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    state: present

- name: Set up keychain for SSH key management
  shell: |
    # Install keychain if not already installed
    which keychain || sudo apt-get install -y keychain
    
    # Start keychain and add your key
    keychain --nogui {{ ansible_env.HOME }}/.ssh/id_ed25519
    
    # Create SSH agent environment file
    keychain --quiet --agents ssh --eval id_ed25519 > ~/.ssh/agent_env
    chmod 600 ~/.ssh/agent_env
  args:
    executable: /bin/bash
