- name: Ensure .ssh directory exists
  file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    mode: '0700'

- name: Add SSH private key (Ed25519)
  copy:
    content: "{{ ssh_private_key }}"
    dest: "{{ ansible_env.HOME }}/.ssh/id_ed25519"
    mode: '0600'
  when: ssh_private_key is defined
  register: ssh_key_added

- name: Add SSH public key (Ed25519)
  copy:
    content: "{{ ssh_public_key }}"
    dest: "{{ ansible_env.HOME }}/.ssh/id_ed25519.pub"
    mode: '0644'
  when: ssh_public_key is defined

- name: Ensure GitHub's SSH key is known
  known_hosts:
    name: github.com
    key: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    state: present

- name: Start SSH agent and store environment
  shell: |
    eval $(ssh-agent -s)
    echo "export SSH_AUTH_SOCK=$SSH_AUTH_SOCK" > ~/.ssh/agent_env
    echo "export SSH_AGENT_PID=$SSH_AGENT_PID" >> ~/.ssh/agent_env
    chmod 600 ~/.ssh/agent_env
  args:
    executable: /bin/bash
    creates: "{{ ansible_env.HOME }}/.ssh/agent_env"

- name: Load SSH agent environment
  shell: |
    source ~/.ssh/agent_env
    ssh-add {{ ansible_env.HOME }}/.ssh/id_ed25519
  args:
    executable: /bin/bash
