---
- name: Ensure .ssh directory exists
  file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    mode: '0700'

- name: Add SSH private key (Ed25519)
  copy:
    content: "{{ ssh_private_key }}"
    dest: "{{ ansible_env.HOME }}/.ssh/id_ed25519"
    mode: '0600'
  when: ssh_private_key is defined
  register: ssh_key_added

- name: Add SSH public key (Ed25519)
  copy:
    content: "{{ ssh_public_key }}"
    dest: "{{ ansible_env.HOME }}/.ssh/id_ed25519.pub"
    mode: '0644'
  when: ssh_public_key is defined

- name: Start SSH agent
  shell: |
    eval $(ssh-agent -s)
    echo $SSH_AUTH_SOCK
  args:
    executable: /bin/bash
  register: ssh_agent_start

- name: Add SSH key to ssh-agent
  shell: |
    SSH_AUTH_SOCK="{{ ssh_agent_start.stdout_lines[-1] }}" ssh-add {{ ansible_env.HOME }}/.ssh/id_ed25519
  args:
    executable: /bin/bash
  register: ssh_add_result

- name: Debug SSH key addition
  debug:
    var: ssh_add_result

- name: Debug SSH keys in agent
  debug:
    var: ssh_keys_in_agent

- name: Set fact for SSH key path
  set_fact:
    ssh_key_path: "{{ ansible_env.HOME }}/.ssh/id_ed25519"

- name: Ensure GitHub's SSH key is known
  known_hosts:
    name: github.com
    key: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    state: present

- name: Test GitHub SSH connection
  shell: ssh -T git@github.com
  register: github_ssh_test
  failed_when: false
  changed_when: false

- name: Show GitHub SSH test result
  debug:
    var: github_ssh_test
