---
- name: Check if Go is installed
  command: which go
  register: go_check
  ignore_errors: yes
  changed_when: false

- name: Get latest Go version
  uri:
    url: https://go.dev/VERSION?m=text
    return_content: yes
  register: go_version_response

- name: Set Go version
  set_fact:
    go_version: "{{ go_version_response.content | regex_replace('^go', '') | regex_replace('\\n.*', '') | trim }}"

- name: Debug Go version
  debug:
    var: go_version

- name: Download the latest Go tarball
  get_url:
    url: "https://go.dev/dl/go{{ go_version }}.linux-amd64.tar.gz"
    dest: /tmp/go.tar.gz
  when: go_check.rc != 0

- name: Extract Go tarball
  unarchive:
    src: /tmp/go.tar.gz
    dest: /usr/local
    remote_src: yes
  become: yes
  when: go_check.rc != 0

- name: Add Go to PATH in shell configuration files
  blockinfile:
    path: "{{ item }}"
    block: |
      export PATH=$PATH:/usr/local/go/bin
      export PATH=$PATH:$HOME/go/bin
    marker: "# {mark} ANSIBLE MANAGED BLOCK - Golang"
  loop:
    - "{{ ansible_env.HOME }}/.bashrc"
    - "{{ ansible_env.HOME }}/.zshrc"

- name: Clean up Go tarball
  file:
    path: /tmp/go.tar.gz
    state: absent
  when: go_check.rc != 0
