- name: Check if fnm is installed
  command: which fnm
  register: fnm_check
  ignore_errors: yes
  changed_when: false

- name: Install fnm
  shell: |
    curl -fsSL https://fnm.vercel.app/install | bash
  args:
    creates: "{{ ansible_env.HOME }}/.fnm"
  when: fnm_check.rc != 0

- name: Add fnm to shell configuration files
  blockinfile:
    path: "{{ item }}"
    block: |
      export PATH=$HOME/.fnm:$PATH
      eval "$(fnm env --use-on-cd)"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - fnm"
  loop:
    - "{{ ansible_env.HOME }}/.bashrc"
    - "{{ ansible_env.HOME }}/.zshrc"

- name: Install latest LTS version of Node.js
  shell: |
    export PATH=$HOME/.fnm:$PATH
    eval "$(fnm env --use-on-cd)"
    fnm install --lts
    fnm default lts-latest
  args:
    executable: /bin/bash
  register: node_install
  changed_when: "'already installed' not in node_install.stderr"
