---
- name: Install Python and related packages
  become: true
  apt:
    name:
      - python3
      - python3-venv
      - python3-pip
      - python3-dev
      - ipython3
      - git
    state: present
  tags:
    - install
    - python

- name: Create a global Python virtual environment
  command: python3 -m venv {{ ansible_env.HOME }}/.venvs/python
  args:
    creates: "{{ ansible_env.HOME }}/.venvs/python"
  tags:
    - python
    - venv

- name: Upgrade pip in global virtual environment
  pip:
    name: pip
    state: latest
    virtualenv: "{{ ansible_env.HOME }}/.venvs/python"
  tags:
    - python
    - pip

- name: Install common Python libraries in global virtual environment
  pip:
    name: 
      - jupyter
      - jupyterlab
      - matplotlib
      - pandas
      - numpy
      - scipy
      - requests
      - beautifulsoup4
      - plotly
      - dash
      - flask
      - sqlalchemy
      - psycopg2-binary
      - nltk
      - tqdm
    state: latest
    virtualenv: "{{ ansible_env.HOME }}/.venvs/python"
  tags:
    - python
    - libraries

- name: Add virtual environment activation alias to shell config
  lineinfile:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    line: 'alias activate_python="source {{ ansible_env.HOME }}/.venvs/python/bin/activate"'
    state: present
  loop:
    - .bashrc
    - .zshrc
  tags:
    - python
    - venv
