---
- name: Ensure .ssh directory exists
  file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    mode: '0700'

- name: Add SSH private key (Ed25519)
  copy:
    content: "{{ ssh_private_key }}"
    dest: "{{ ansible_env.HOME }}/.ssh/id_ed25519"
    mode: '0600'
  when: ssh_private_key is defined

- name: Add SSH public key (Ed25519)
  copy:
    content: "{{ ssh_public_key }}"
    dest: "{{ ansible_env.HOME }}/.ssh/id_ed25519.pub"
    mode: '0644'
  when: ssh_public_key is defined

- name: Start SSH agent
  shell: |
    eval $(ssh-agent -s)
    echo $SSH_AUTH_SOCK
  args:
    executable: /bin/bash
  register: ssh_agent_start

- name: Debug SSH agent start
  debug:
    var: ssh_agent_start

- name: Add SSH key to ssh-agent
  shell: |
    SSH_AUTH_SOCK="{{ ssh_agent_start.stdout_lines[-1] }}" ssh-add {{ ansible_env.HOME }}/.ssh/id_ed25519
  args:
    executable: /bin/bash
  register: ssh_add_result
  changed_when: "'Identity added' in ssh_add_result.stdout"
  failed_when: 
    - ssh_add_result.rc != 0 
    - "'Identity added' not in ssh_add_result.stdout"
    - "'Already added' not in ssh_add_result.stderr"

- name: Debug ssh-add result
  debug:
    var: ssh_add_result
