- name: Add SSH private key
  copy:
    content: "{{ ssh_private_key }}"
    dest: "{{ ansible_env.HOME }}/.ssh/id_ed25519"
    mode: '0600'
  when: ssh_private_key is defined

- name: Add SSH public key
  copy:
    content: "{{ ssh_public_key }}"
    dest: "{{ ansible_env.HOME }}/.ssh/id_ed25519.pub"
    mode: '0644'
  when: ssh_public_key is defined
