- name: Ensure .ssh directory exists
  file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    mode: '0700'

- name: Add SSH private key (Ed25519)
  copy:
    content: "{{ ssh_private_key }}"
    dest: "{{ ansible_env.HOME }}/.ssh/id_ed25519"
    mode: '0600'
  when: ssh_private_key is defined

- name: Add SSH public key (Ed25519)
  copy:
    content: "{{ ssh_public_key }}"
    dest: "{{ ansible_env.HOME }}/.ssh/id_ed25519.pub"
    mode: '0644'
  when: ssh_public_key is defined

- name: Ensure ssh-agent is running
  shell: |
    if ! pgrep -u "$USER" ssh-agent > /dev/null; then
      ssh-agent > ~/.ssh-agent-thing
    fi
  args:
    executable: /bin/bash
    creates: ~/.ssh-agent-thing

- name: Load SSH key into ssh-agent
  shell: |
    source ~/.ssh-agent-thing
    ssh-add {{ ansible_env.HOME }}/.ssh/id_ed25519
  args:
    executable: /bin/bash
  register: ssh_add_result
  changed_when: "'Identity added' in ssh_add_result.stdout"
  failed_when: 
    - ssh_add_result.rc != 0 
    - "'Identity added' not in ssh_add_result.stdout"
    - "'Already added' not in ssh_add_result.stderr"

- name: Ensure .bashrc loads ssh-agent
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: "source ~/.ssh-agent-thing"
    state: present
